/* Copyright 2014 Google */ (function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,m=function(){},n=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},aa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ba=function(a,b,c){return a.call.apply(a.bind,arguments)},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return a.apply(b,d)}}return function(){return a.apply(b,
arguments)}},p=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?p=ba:p=ca;return p.apply(null,arguments)},q=function(a,b){function c(){}c.prototype=b.prototype;a.O=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.N=function(e,d,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[d].apply(e,g)}},r=function(a){return a};function t(a,b){return a.replace(/\{\{\$.*?\}\}/g,function(c){c=c.substr(3,c.length-5);return String(b[c])||""})}function u(a){a=String(a).toLowerCase().replace("_","-");if("zh-cn"==a)return"zh-CN";if("zh-tw"==a)return"zh-TW";var b=a.indexOf("-");a=0<=b?a.substring(0,b):a;return"zh"==a?"zh-CN":a};function v(a){if(Error.captureStackTrace)Error.captureStackTrace(this,v);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}q(v,Error);v.prototype.name="CustomError";function w(a,b){a=a.split("%s");for(var c="",e=a.length-1,d=0;d<e;d++)c+=a[d]+(d<b.length?b[d]:"%s");v.call(this,c+a[e])}q(w,v);w.prototype.name="AssertionError";function da(a,b,c,e){var d="Assertion failed";if(c){d+=": "+c;var f=e}else a&&(d+=": "+a,f=b);throw new w(""+d,f||[]);}
var x=function(a,b,c){a||da("",null,b,Array.prototype.slice.call(arguments,2));return a},y=function(a,b){throw new w("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},z=function(a,b,c){"function"!==typeof a&&da("Expected function but got %s: %s.",[n(a),a],b,Array.prototype.slice.call(arguments,2))};var A;var B=function(a,b){this.g=a===fa&&b||"";this.h=ha};B.prototype.B=!0;B.prototype.v=function(){return this.g};B.prototype.toString=function(){return"Const{"+this.g+"}"};var ha={},fa={};var C=function(a,b){this.g=b===ia?a:""};C.prototype.B=!0;C.prototype.v=function(){return this.g.toString()};C.prototype.toString=function(){return this.g+""};
var D=function(a){if(a instanceof C&&a.constructor===C)return a.g;y("expected object of type TrustedResourceUrl, got '"+a+"' of type "+n(a));return"type_error:TrustedResourceUrl"},ja=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ia={},ka=function(a){if(void 0===A){var b=null;var c=k.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:r,createScript:r,createScriptURL:r})}catch(e){k.console&&k.console.error(e.message)}A=b}else A=b}a=(b=A)?b.createScriptURL(a):a;return new C(a,ia)},la=
function(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var e in c)if(Object.prototype.hasOwnProperty.call(c,e)){var d=c[e];d=Array.isArray(d)?d:[d];for(var f=0;f<d.length;f++){var g=d[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(e)+"="+encodeURIComponent(String(g)))}}return b};var ma=Array.prototype.some?function(a,b){x(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,d=0;d<c;d++)if(d in e&&b.call(void 0,e[d],d,a))return!0;return!1};function E(){var a=k.navigator;return a&&(a=a.userAgent)?a:""};var na=function(a,b){a:{try{var c=a&&a.ownerDocument,e=c&&(c.defaultView||c.parentWindow);e=e||k;if(e.Element&&e.Location){var d=e;break a}}catch(g){}d=null}if(d&&"undefined"!=typeof d[b]&&(!a||!(a instanceof d[b])&&(a instanceof d.Location||a instanceof d.Element))){if(aa(a))try{var f=a.constructor.displayName||a.constructor.name||Object.prototype.toString.call(a)}catch(g){f="<object could not be stringified>"}else f=void 0===a?"undefined":null===a?"null":typeof a;y("Argument is not a %s (or a non-Element, non-Location mock); got: %s",
b,f)}};function oa(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var pa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function qa(a,b){for(var c,e,d=1;d<arguments.length;d++){e=arguments[d];for(c in e)a[c]=e[c];for(var f=0;f<pa.length;f++)c=pa[f],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};var G=function(a,b){this.g=b===F?a:""};G.prototype.B=!0;G.prototype.v=function(){return this.g.toString()};G.prototype.toString=function(){return this.g.toString()};var ra=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,sa=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,F={},ta=new G("about:invalid#zClosurez",F);var ua=function(a){var b=H;na(b,"HTMLAudioElement");if(a instanceof G)var c=a;else a:if(c=a,a=/^data:audio\//i.test(a),!(c instanceof G)){c="object"==typeof c&&c.B?c.v():String(c);if(a&&/^data:/i.test(c)&&(a=String(c),a=a.replace(/(%0A|%0D)/g,""),a=(a.match(ra)?new G(a,F):null)||ta,a.v()==c)){c=a;break a}x(sa.test(c),"%s does not match the safe URL pattern",c)||(c="about:invalid#zClosurez");c=new G(c,F)}c instanceof G&&c.constructor===G?c=c.g:(y("expected object of type SafeUrl, got '"+c+"' of type "+
n(c)),c="type_error:SafeUrl");b.src=c},wa=function(a,b){na(a,"HTMLScriptElement");a:{var c=(a.ownerDocument&&a.ownerDocument.defaultView||k).document;if(c.querySelector&&(c=c.querySelector("script[nonce]"))&&(c=c.nonce||c.getAttribute("nonce"))&&va.test(c))break a;c=""}c&&a.setAttribute("nonce",c);a.src=D(b)},va=/^[\w+/_-]+[=]{0,2}$/;var ya=function(a,b){oa(b,function(c,e){c&&"object"==typeof c&&c.B&&(c=c.v());"style"==e?a.style.cssText=c:"class"==e?a.className=c:"for"==e?a.htmlFor=c:xa.hasOwnProperty(e)?a.setAttribute(xa[e],c):0==e.lastIndexOf("aria-",0)||0==e.lastIndexOf("data-",0)?a.setAttribute(e,c):a[e]=c})},xa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",
width:"width"},I=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},J=function(a){this.g=a||k.document||document};J.prototype.setProperties=ya;J.prototype.getChildren=function(a){return void 0!=a.children?a.children:Array.prototype.filter.call(a.childNodes,function(b){return 1==b.nodeType})};
J.prototype.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var K=function(a,b){this.i=a;this.j=b;this.h=0;this.g=null};K.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};var za=function(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};var L,Aa=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&-1==E().indexOf("Presto")&&(a=function(){var d=I(document,"IFRAME");d.style.display="none";document.documentElement.appendChild(d);var f=d.contentWindow;d=f.document;d.open();d.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;d=p(function(l){if(("*"==h||l.origin==h)&&l.data==g)this.port1.onmessage()},
this);f.addEventListener("message",d,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&-1==E().indexOf("Trident")&&-1==E().indexOf("MSIE")){var b=new a,c={},e=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var d=c.J;c.J=null;d()}};return function(d){e.next={J:d};e=e.next;b.port2.postMessage(0)}}return function(d){k.setTimeout(d,0)}};function Ba(a){k.setTimeout(function(){throw a;},0)};var Ca=function(){this.h=this.g=null};Ca.prototype.add=function(a,b){var c=Da.get();c.set(a,b);this.h?this.h.next=c:(x(!this.g),this.g=c);this.h=c};Ca.prototype.remove=function(){var a=null;this.g&&(a=this.g,this.g=this.g.next,this.g||(this.h=null),a.next=null);return a};var Da=new K(function(){return new Ea},function(a){return a.reset()}),Ea=function(){this.next=this.g=this.h=null};Ea.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};
Ea.prototype.reset=function(){this.next=this.g=this.h=null};var Ia=function(a,b){M||Fa();Ga||(M(),Ga=!0);Ha.add(a,b)},M,Fa=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve(void 0);M=function(){a.then(Ja)}}else M=function(){var b=Ja,c;!(c="function"!==typeof k.setImmediate)&&(c=k.Window&&k.Window.prototype)&&(c=-1==E().indexOf("Edge")&&k.Window.prototype.setImmediate==k.setImmediate);c?(L||(L=Aa()),L(b)):k.setImmediate(b)}},Ga=!1,Ha=new Ca,Ja=function(){for(var a;a=Ha.remove();){try{a.h.call(a.g)}catch(b){Ba(b)}za(Da,a)}Ga=!1};var Ka=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var P=function(a){this.g=0;this.s=void 0;this.j=this.h=this.i=null;this.l=this.m=!1;if(a!=m)try{var b=this;a.call(void 0,function(c){N(b,2,c)},function(c){if(!(c instanceof O))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(e){}N(b,3,c)})}catch(c){N(this,3,c)}},La=function(){this.next=this.j=this.i=this.h=this.g=null;this.l=!1};La.prototype.reset=function(){this.j=this.i=this.h=this.g=null;this.l=!1};
var Ma=new K(function(){return new La},function(a){a.reset()}),Na=function(a,b,c){var e=Ma.get();e.h=a;e.i=b;e.j=c;return e};P.prototype.then=function(a,b,c){null!=a&&z(a,"opt_onFulfilled should be a function.");null!=b&&z(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Oa(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};P.prototype.$goog_Thenable=!0;
P.prototype.cancel=function(a){if(0==this.g){var b=new O(a);Ia(function(){Pa(this,b)},this)}};
var Pa=function(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var e=0,d=null,f=null,g=c.h;g&&(g.l||(e++,g.g==a&&(d=g),!(d&&1<e)));g=g.next)d||(f=g);d&&(0==c.g&&1==e?Pa(c,b):(f?(e=f,x(c.h),x(null!=e),e.next==c.j&&(c.j=e),e.next=e.next.next):Qa(c),Ra(c,d,3,b)))}a.i=null}else N(a,3,b)},Ta=function(a,b){a.h||2!=a.g&&3!=a.g||Sa(a);x(null!=b.h);a.j?a.j.next=b:a.h=b;a.j=b},Oa=function(a,b,c,e){var d=Na(null,null,null);d.g=new P(function(f,g){d.h=b?function(h){try{var l=b.call(e,h);f(l)}catch(ea){g(ea)}}:
f;d.i=c?function(h){try{var l=c.call(e,h);void 0===l&&h instanceof O?g(h):f(l)}catch(ea){g(ea)}}:g});d.g.i=a;Ta(a,d);return d.g};P.prototype.A=function(a){x(1==this.g);this.g=0;N(this,2,a)};P.prototype.D=function(a){x(1==this.g);this.g=0;N(this,3,a)};
var N=function(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var e=c,d=a.A,f=a.D;if(e instanceof P){null!=d&&z(d,"opt_onFulfilled should be a function.");null!=f&&z(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Ta(e,Na(d||m,f||null,a));var g=!0}else if(Ka(e))e.then(d,f,a),g=!0;else{if(aa(e))try{var h=e.then;if("function"===typeof h){Ua(e,h,d,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;
break a}g=!1}}g||(a.s=c,a.g=b,a.i=null,Sa(a),3!=b||c instanceof O||Va(a,c))}},Ua=function(a,b,c,e,d){var f=!1,g=function(l){f||(f=!0,c.call(d,l))},h=function(l){f||(f=!0,e.call(d,l))};try{b.call(a,g,h)}catch(l){h(l)}},Sa=function(a){a.m||(a.m=!0,Ia(a.u,a))},Qa=function(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);null!=b&&x(null!=b.h);return b};P.prototype.u=function(){for(var a;a=Qa(this);)Ra(this,a,this.g,this.s);this.m=!1};
var Ra=function(a,b,c,e){if(3==c&&b.i&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,Wa(b,c,e);else try{b.l?b.h.call(b.j):Wa(b,c,e)}catch(d){Xa.call(null,d)}za(Ma,b)},Wa=function(a,b,c){2==b?a.h.call(a.j,c):a.i&&a.i.call(a.j,c)},Va=function(a,b){a.l=!0;Ia(function(){a.l&&Xa.call(null,b)})},Xa=Ba,O=function(a){v.call(this,a)};q(O,v);O.prototype.name="cancel";/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
var Q=function(a){var b=Ya;this.l=[];this.I=b;this.H=a||null;this.j=this.i=!1;this.h=void 0;this.A=this.D=this.s=!1;this.m=0;this.g=null;this.u=0};Q.prototype.cancel=function(a){if(this.i)this.h instanceof Q&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.u--,0>=b.u&&b.cancel())}this.I?this.I.call(this.H,this):this.A=!0;this.i||Za(this,new R(this))}};Q.prototype.G=function(a,b){this.s=!1;$a(this,a,b)};
var $a=function(a,b,c){a.i=!0;a.h=c;a.j=!b;ab(a)},bb=function(a){if(a.i){if(!a.A)throw new S(a);a.A=!1}},Za=function(a,b){bb(a);cb(b);$a(a,!1,b)},cb=function(a){x(!(a instanceof Q),"An execution sequence may not be initiated with a blocking Deferred.")},db=function(a,b,c,e){x(!a.D,"Blocking Deferreds can not be re-used");a.l.push([b,c,e]);a.i&&ab(a)};Q.prototype.then=function(a,b,c){var e,d,f=new P(function(g,h){d=g;e=h});db(this,d,function(g){g instanceof R?f.cancel():e(g)});return f.then(a,b,c)};
Q.prototype.$goog_Thenable=!0;Q.prototype.isError=function(a){return a instanceof Error};
var eb=function(a){return ma(a.l,function(b){return"function"===typeof b[1]})},ab=function(a){if(a.m&&a.i&&eb(a)){var b=a.m,c=T[b];c&&(k.clearTimeout(c.o),delete T[b]);a.m=0}a.g&&(a.g.u--,delete a.g);b=a.h;for(var e=c=!1;a.l.length&&!a.s;){var d=a.l.shift(),f=d[0],g=d[1];d=d[2];if(f=a.j?g:f)try{var h=f.call(d||a.H,b);void 0!==h&&(a.j=a.j&&(h==b||a.isError(h)),a.h=b=h);if(Ka(b)||"function"===typeof k.Promise&&b instanceof k.Promise)e=!0,a.s=!0}catch(l){b=l,a.j=!0,eb(a)||(c=!0)}}a.h=b;e&&(h=p(a.G,a,
!0),e=p(a.G,a,!1),b instanceof Q?(db(b,h,e),b.D=!0):b.then(h,e));c&&(b=new fb(b),T[b.o]=b,a.m=b.o)},S=function(){v.call(this)};q(S,v);S.prototype.message="Deferred has already fired";S.prototype.name="AlreadyCalledError";var R=function(){v.call(this)};q(R,v);R.prototype.message="Deferred was canceled";R.prototype.name="CanceledError";var fb=function(a){this.o=k.setTimeout(p(this.h,this),0);this.g=a};
fb.prototype.h=function(){x(T[this.o],"Cannot throw an error that is not scheduled.");delete T[this.o];throw this.g;};var T={};var ib=function(a,b){var c=b||{};b=c.document||document;var e=D(a).toString(),d=I((new J(b)).g,"SCRIPT"),f={L:d,C:void 0},g=new Q(f),h=null,l=null!=c.timeout?c.timeout:5E3;0<l&&(h=window.setTimeout(function(){U(d,!0);Za(g,new gb(1,"Timeout reached for loading script "+e))},l),f.C=h);d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||(U(d,c.M||!1,h),bb(g),cb(null),$a(g,!0,null))};d.onerror=function(){U(d,!0,h);Za(g,new gb(0,"Error while loading script "+
e))};f=c.attributes||{};qa(f,{type:"text/javascript",charset:"UTF-8"});ya(d,f);wa(d,a);hb(b).appendChild(d);return g},hb=function(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement},Ya=function(){if(this&&this.L){var a=this.L;a&&"SCRIPT"==a.tagName&&U(a,!0,this.C)}},U=function(a,b,c){null!=c&&k.clearTimeout(c);a.onload=m;a.onerror=m;a.onreadystatechange=m;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)},gb=function(a,
b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);v.call(this,c);this.code=a};q(gb,v);var jb=function(a){this.g=a;this.C=5E3},kb=0;jb.prototype.send=function(a,b,c,e){if(a){var d={};for(f in a)d[f]=a[f];a=d}else a={};e=e||"_"+(kb++).toString(36)+Date.now().toString(36);d="_callbacks___"+e;b&&(k[d]=lb(e,b),a.cb=d);b={timeout:this.C,M:!0};d=D(this.g).toString();d=ja.exec(d);var f=d[3]||"";d=ka(d[1]+la("?",d[2]||"",a)+la("#",f,void 0));b=ib(d,b);db(b,null,mb(e,a,c),void 0);return{o:e,K:b}};jb.prototype.cancel=function(a){a&&(a.K&&a.K.cancel(),a.o&&nb(a.o,!1))};
var mb=function(a,b,c){return function(){nb(a,!1);c&&c(b)}},lb=function(a,b){return function(c){nb(a,!0);b.apply(void 0,arguments)}},nb=function(a,b){a="_callbacks___"+a;if(k[a])if(b)try{delete k[a]}catch(c){k[a]=void 0}else k[a]=m};var V=function(){this.h=[];chrome.i18n.getAcceptLanguages(p(this.m,this));this.g="";this.j="1";this.i={};chrome.storage.local.get(null,p(this.u,this));ob(this)},qb=function(){var a=pb;if(""!=a.g)a=a.g;else a:{for(var b=0;b<a.h.length;b++){var c=u(a.h[b]);if(a.i[c]){a=c;break a}}a="en"}return a};
V.prototype.u=function(a){"gtxTargetLang"in a&&(this.g=a.gtxTargetLang);"gtxShowBubble"in a&&(this.j=a.gtxShowBubble);"gtxSourceLangList"in a&&rb(this,a.gtxSourceLangList);"gtxTargetLangList"in a&&(this.i=rb(this,a.gtxTargetLangList));this.loaded=!0;var b=(new Date).getTime(),c="gtxTimeStamp"in a?a.gtxTimeStamp:0,e=chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():"en";a="gtxDisplayLanguage"in a?a.gtxDisplayLanguage:"";if(864E5<Math.abs(b-c)||e!=a)b=new B(fa,"https://translate.googleapis.com/translate_a/l"),
b instanceof B&&b.constructor===B&&b.h===ha?b=b.g:(y("expected object of type Const, got '"+b+"'"),b="type_error:Const"),b=ka(b),(new jb(b)).send({client:"gtx",hl:e},p(this.s,this,e))};var rb=function(a,b){var c=[],e;for(e in b)c.push({code:e,name:b[e]});c.sort(a.l);a={};for(b=0;b<c.length;b++)a[c[b].code]=c[b].name;return a};V.prototype.l=function(a,b){return a.name.localeCompare(b.name)};
var ob=function(a){chrome.storage.onChanged.addListener(function(b){b.gtxTargetLang&&(a.g=b.gtxTargetLang.newValue);b.gtxShowBubble&&(a.j=b.gtxShowBubble.newValue)})};V.prototype.m=function(a){this.h=a};V.prototype.s=function(a,b){var c=(new Date).getTime(),e={};e.gtxSourceLangList=b.sl;e.gtxTargetLangList=b.tl;e.gtxDisplayLanguage=a;e.gtxTimeStamp=c;chrome.storage.local.set(e);this.i=b.tl};var sb=t("(function(){({{$code}})();})();",{code:window.injection.toString()}),tb=t("(function(){({{$code}})();})();",{code:window.injector.toString()}),ub=/^[A-z-]{2,}$/;delete window.injector;delete window.injection;
function vb(a,b,c){if(!ub.test(c))throw Error("Invalid language in local storage!");b={pageLang:b,userLang:c};b.content=t(sb,b).replace(/\\/g,"\\\\").replace(/'/g,"\\'").replace(/"/g,'\\"').replace(/\n/g,"\\n");chrome.tabs.executeScript(a,{code:t(tb,b)},function(){chrome.runtime.lastError&&console.error(chrome.runtime.lastError.message)})}var wb=function(a){this.i=a;this.F=this.g=!1};wb.prototype.popup=function(){this.g||this.F||(this.g=!0,this.h="",chrome.tabs.detectLanguage(this.i,p(this.j,this)))};
wb.prototype.j=function(a){if(!this.F){if(!a||"und"==a||a.match("invalid"))a="auto";this.h=a;a=u(qb());var b=u(this.h);vb(this.i,b,a);this.g=!1}};var W=function(){this.g={}};W.prototype.attach=function(a){this.g[a]||(this.g[a]=new wb(a));this.g[a].popup()};W.prototype.detach=function(a){this.g[a]&&(this.g[a].F=!0,delete this.g[a])};var xb=new W,pb=new V,H=I(document,"AUDIO");
chrome.runtime.onMessage.addListener(function(a,b){a.audioSrc?H.paused||a.audioSrc!=H.src?(ua(a.audioSrc),H.load(),H.play()):(H.pause(),H.currentTime=0):a.bubbleClosed||a.popupClosed?H.pause():a.detectLanguage&&chrome.tabs.detectLanguage(function(c){chrome.tabs.sendMessage(b.tab.id,{"gtx.detected":c})})});chrome.runtime.onConnect.addListener(function(a){a.onDisconnect.addListener(function(){chrome.runtime.sendMessage({popupClosed:!0})})});
chrome.runtime.onInstalled.addListener(function(){var a=chrome.contextMenus,b=a.create;var c=chrome.i18n.getMessage("MSG_FOOTER_TRANSLATE");c=chrome.i18n.getMessage(c);b.call(a,{id:"translate",title:c,contexts:["selection"]})});chrome.contextMenus.onClicked.addListener(function(a){var b=chrome.tabs,c=b.create;a="https://translate.google.com/?source=gtx_c#auto/"+qb()+"/"+encodeURIComponent(a.selectionText);c.call(b,{url:a})});var yb=function(){return xb},X=["translate","getTranslateManager"],Y=k;
X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===yb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=yb;W.prototype.attach=W.prototype.attach;W.prototype.detach=W.prototype.detach;})();
